/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authVerify } from "../funcs/authVerify.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Auth extends ClientSDK {
  /**
   * Verify API Credentials
   */
  async verify(
    options?: RequestOptions,
  ): Promise<operations.PostV1AuthVerifyResponse> {
    return unwrapAsync(authVerify(
      this,
      options,
    ));
  }
}
