/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { bansGetRecent } from "../funcs/bansGetRecent.js";
import { bansGetStats } from "../funcs/bansGetStats.js";
import { bansGetTrends } from "../funcs/bansGetTrends.js";
import { bansSearch } from "../funcs/bansSearch.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Bans extends ClientSDK {
  /**
   * Recent Bans
   *
   * @remarks
   * Cost 2
   */
  async getRecent(
    request?: operations.GetV1BansRecentRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetV1BansRecentResponse> {
    return unwrapAsync(bansGetRecent(
      this,
      request,
      options,
    ));
  }

  /**
   * Search Bans
   *
   * @remarks
   * Cost 5
   */
  async search(
    request?: operations.GetV1BansSearchRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetV1BansSearchResponse> {
    return unwrapAsync(bansSearch(
      this,
      request,
      options,
    ));
  }

  /**
   * Ban Stats
   *
   * @remarks
   * Cost 5
   */
  async getStats(
    request?: operations.GetV1BansStatsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetV1BansStatsResponse> {
    return unwrapAsync(bansGetStats(
      this,
      request,
      options,
    ));
  }

  /**
   * Ban Trends
   *
   * @remarks
   * Cost 10
   */
  async getTrends(
    request?: operations.GetV1BansTrendsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetV1BansTrendsResponse> {
    return unwrapAsync(bansGetTrends(
      this,
      request,
      options,
    ));
  }
}
