/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { keysGetUsage } from "../funcs/keysGetUsage.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Keys extends ClientSDK {
  /**
   * Get Usage Stats
   */
  async getUsage(
    options?: RequestOptions,
  ): Promise<operations.GetV1KeysUsageResponse> {
    return unwrapAsync(keysGetUsage(
      this,
      options,
    ));
  }
}
