/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { playerAnalyze } from "../funcs/playerAnalyze.js";
import { playerDiscordLookup } from "../funcs/playerDiscordLookup.js";
import { playerGet } from "../funcs/playerGet.js";
import { playerGetBans } from "../funcs/playerGetBans.js";
import { playerGetBansHistory } from "../funcs/playerGetBansHistory.js";
import { playerGetServers } from "../funcs/playerGetServers.js";
import { playerGetThreatScore } from "../funcs/playerGetThreatScore.js";
import { playerSearch } from "../funcs/playerSearch.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Player extends ClientSDK {
  /**
   * Search Players
   *
   * @remarks
   * Cost 5
   */
  async search(
    request: operations.GetV1PlayerSearchRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1PlayerSearchResponse> {
    return unwrapAsync(playerSearch(
      this,
      request,
      options,
    ));
  }

  /**
   * Player Profile
   *
   * @remarks
   * Cost 5
   */
  async get(
    request: operations.GetV1PlayerIdentifierRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1PlayerIdentifierResponse> {
    return unwrapAsync(playerGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Server History
   *
   * @remarks
   * Cost 5
   */
  async getServers(
    request: operations.GetV1PlayerIdentifierServersRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1PlayerIdentifierServersResponse> {
    return unwrapAsync(playerGetServers(
      this,
      request,
      options,
    ));
  }

  /**
   * Player Active Bans
   *
   * @remarks
   * Cost 5
   */
  async getBans(
    request: operations.GetV1PlayerIdentifierBansRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1PlayerIdentifierBansResponse> {
    return unwrapAsync(playerGetBans(
      this,
      request,
      options,
    ));
  }

  /**
   * Player Ban History
   *
   * @remarks
   * Cost 10
   */
  async getBansHistory(
    request: operations.GetV1PlayerIdentifierBansHistoryRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1PlayerIdentifierBansHistoryResponse> {
    return unwrapAsync(playerGetBansHistory(
      this,
      request,
      options,
    ));
  }

  /**
   * Threat Score
   *
   * @remarks
   * Cost 5
   */
  async getThreatScore(
    request: operations.GetV1PlayerIdentifierThreatScoreRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1PlayerIdentifierThreatScoreResponse> {
    return unwrapAsync(playerGetThreatScore(
      this,
      request,
      options,
    ));
  }

  /**
   * Player Analysis
   *
   * @remarks
   * Performs a deep analysis of the player, including alt accounts, bans, and threat score.
   * (Cost: 15)
   */
  async analyze(
    request: operations.GetV1PlayerIdentifierAnalysisRequest,
    options?: RequestOptions,
  ): Promise<models.PlayerAnalysis> {
    return unwrapAsync(playerAnalyze(
      this,
      request,
      options,
    ));
  }

  /**
   * Discord Lookup
   *
   * @remarks
   * Cost 5
   */
  async discordLookup(
    request: operations.GetV1PlayerIdentifierDiscordLookupRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1PlayerIdentifierDiscordLookupResponse> {
    return unwrapAsync(playerDiscordLookup(
      this,
      request,
      options,
    ));
  }
}
