/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Auth } from "./auth.js";
import { Bans } from "./bans.js";
import { Keys } from "./keys.js";
import { Player } from "./player.js";
import { Server } from "./server.js";
import { Stats } from "./stats.js";
import { Webhooks } from "./webhooks.js";

export class WaveShield extends ClientSDK {
  private _auth?: Auth;
  get auth(): Auth {
    return (this._auth ??= new Auth(this._options));
  }

  private _keys?: Keys;
  get keys(): Keys {
    return (this._keys ??= new Keys(this._options));
  }

  private _stats?: Stats;
  get stats(): Stats {
    return (this._stats ??= new Stats(this._options));
  }

  private _bans?: Bans;
  get bans(): Bans {
    return (this._bans ??= new Bans(this._options));
  }

  private _server?: Server;
  get server(): Server {
    return (this._server ??= new Server(this._options));
  }

  private _player?: Player;
  get player(): Player {
    return (this._player ??= new Player(this._options));
  }

  private _webhooks?: Webhooks;
  get webhooks(): Webhooks {
    return (this._webhooks ??= new Webhooks(this._options));
  }
}
