/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { serverAddAdmin } from "../funcs/serverAddAdmin.js";
import { serverBan } from "../funcs/serverBan.js";
import { serverBanOffline } from "../funcs/serverBanOffline.js";
import { serverExecuteCommand } from "../funcs/serverExecuteCommand.js";
import { serverGetAdmins } from "../funcs/serverGetAdmins.js";
import { serverGetBan } from "../funcs/serverGetBan.js";
import { serverGetBanHistory } from "../funcs/serverGetBanHistory.js";
import { serverGetBans } from "../funcs/serverGetBans.js";
import { serverGetConfig } from "../funcs/serverGetConfig.js";
import { serverGetInfo } from "../funcs/serverGetInfo.js";
import { serverGetLogs } from "../funcs/serverGetLogs.js";
import { serverGetPlayers } from "../funcs/serverGetPlayers.js";
import { serverGetStats } from "../funcs/serverGetStats.js";
import { serverKick } from "../funcs/serverKick.js";
import { serverLookupPlayer } from "../funcs/serverLookupPlayer.js";
import { serverRemoveAdmin } from "../funcs/serverRemoveAdmin.js";
import { serverRequestScreenshot } from "../funcs/serverRequestScreenshot.js";
import { serverUnban } from "../funcs/serverUnban.js";
import { serverUnbanAll } from "../funcs/serverUnbanAll.js";
import { serverUnbanLast } from "../funcs/serverUnbanLast.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Server extends ClientSDK {
  /**
   * Server Info
   *
   * @remarks
   * Cost 2
   */
  async getInfo(
    options?: RequestOptions,
  ): Promise<operations.GetV1ServerResponse> {
    return unwrapAsync(serverGetInfo(
      this,
      options,
    ));
  }

  /**
   * Server Statistics
   *
   * @remarks
   * Cost 5
   */
  async getStats(
    request?: operations.GetV1ServerStatsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetV1ServerStatsResponse> {
    return unwrapAsync(serverGetStats(
      this,
      request,
      options,
    ));
  }

  /**
   * Server Active Bans
   *
   * @remarks
   * Cost 5
   */
  async getBans(
    request?: operations.GetV1ServerBansRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetV1ServerBansResponse> {
    return unwrapAsync(serverGetBans(
      this,
      request,
      options,
    ));
  }

  /**
   * Server Ban History
   *
   * @remarks
   * Cost 5
   */
  async getBanHistory(
    request?: operations.GetV1ServerBansHistoryRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetV1ServerBansHistoryResponse> {
    return unwrapAsync(serverGetBanHistory(
      this,
      request,
      options,
    ));
  }

  /**
   * Server Config
   *
   * @remarks
   * Cost 2
   */
  async getConfig(
    options?: RequestOptions,
  ): Promise<operations.GetV1ServerConfigResponse> {
    return unwrapAsync(serverGetConfig(
      this,
      options,
    ));
  }

  /**
   * Online Players List
   *
   * @remarks
   * Cost 2
   */
  async getPlayers(
    options?: RequestOptions,
  ): Promise<operations.GetV1ServerPlayersResponse> {
    return unwrapAsync(serverGetPlayers(
      this,
      options,
    ));
  }

  /**
   * Server Admins
   *
   * @remarks
   * Cost 2
   */
  async getAdmins(
    options?: RequestOptions,
  ): Promise<operations.GetV1ServerAdminsResponse> {
    return unwrapAsync(serverGetAdmins(
      this,
      options,
    ));
  }

  /**
   * Server Logs
   *
   * @remarks
   * Cost 10
   */
  async getLogs(
    request?: operations.GetV1ServerLogsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetV1ServerLogsResponse> {
    return unwrapAsync(serverGetLogs(
      this,
      request,
      options,
    ));
  }

  /**
   * Lookup Player
   *
   * @remarks
   * Cost 15
   */
  async lookupPlayer(
    request: operations.PostV1ServerLookupRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1ServerLookupResponse> {
    return unwrapAsync(serverLookupPlayer(
      this,
      request,
      options,
    ));
  }

  /**
   * Request Screenshot
   *
   * @remarks
   * Cost 10
   */
  async requestScreenshot(
    request: operations.PostV1ServerScreenshotRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1ServerScreenshotResponse> {
    return unwrapAsync(serverRequestScreenshot(
      this,
      request,
      options,
    ));
  }

  /**
   * Kick Player
   *
   * @remarks
   * Cost 5
   */
  async kick(
    request: operations.PostV1ServerKickRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1ServerKickResponse> {
    return unwrapAsync(serverKick(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Ban Info
   *
   * @remarks
   * Cost 2
   */
  async getBan(
    request: operations.GetV1ServerBanRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1ServerBanResponse> {
    return unwrapAsync(serverGetBan(
      this,
      request,
      options,
    ));
  }

  /**
   * Ban Player
   *
   * @remarks
   * Cost 5
   */
  async ban(
    request: operations.PostV1ServerBanRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1ServerBanResponse> {
    return unwrapAsync(serverBan(
      this,
      request,
      options,
    ));
  }

  /**
   * Ban Player Offline
   *
   * @remarks
   * Cost 10
   */
  async banOffline(
    request: operations.PostV1ServerBanOfflineRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1ServerBanOfflineResponse> {
    return unwrapAsync(serverBanOffline(
      this,
      request,
      options,
    ));
  }

  /**
   * Unban Player
   *
   * @remarks
   * Cost 5
   */
  async unban(
    request: operations.PostV1ServerUnbanRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1ServerUnbanResponse> {
    return unwrapAsync(serverUnban(
      this,
      request,
      options,
    ));
  }

  /**
   * Unban Last Players
   *
   * @remarks
   * Cost 10
   */
  async unbanLast(
    request?: operations.PostV1ServerUnbanLastRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.PostV1ServerUnbanLastResponse> {
    return unwrapAsync(serverUnbanLast(
      this,
      request,
      options,
    ));
  }

  /**
   * Unban All Players
   *
   * @remarks
   * Cost 50
   */
  async unbanAll(
    options?: RequestOptions,
  ): Promise<operations.PostV1ServerUnbanAllResponse> {
    return unwrapAsync(serverUnbanAll(
      this,
      options,
    ));
  }

  /**
   * Execute Console Command
   *
   * @remarks
   * Cost 5
   */
  async executeCommand(
    request: operations.PostV1ServerExecRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1ServerExecResponse> {
    return unwrapAsync(serverExecuteCommand(
      this,
      request,
      options,
    ));
  }

  /**
   * Add Admin
   *
   * @remarks
   * Cost 5
   */
  async addAdmin(
    request: operations.PostV1ServerAdminAddRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1ServerAdminAddResponse> {
    return unwrapAsync(serverAddAdmin(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove Admin
   *
   * @remarks
   * Cost 5
   */
  async removeAdmin(
    request: operations.PostV1ServerAdminRemoveRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1ServerAdminRemoveResponse> {
    return unwrapAsync(serverRemoveAdmin(
      this,
      request,
      options,
    ));
  }
}
