/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksCreate } from "../funcs/webhooksCreate.js";
import { webhooksDelete } from "../funcs/webhooksDelete.js";
import { webhooksList } from "../funcs/webhooksList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Webhooks extends ClientSDK {
  /**
   * List Active Webhooks
   *
   * @remarks
   * Coming Soon
   */
  async list(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(webhooksList(
      this,
      options,
    ));
  }

  /**
   * Create Webhook
   *
   * @remarks
   * Coming Soon.
   * Events: player_banned, player_first_time_seen
   */
  async create(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(webhooksCreate(
      this,
      options,
    ));
  }

  /**
   * Delete Webhook
   *
   * @remarks
   * Coming Soon
   */
  async delete(
    request: operations.DeleteV1WebhooksIdRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(webhooksDelete(
      this,
      request,
      options,
    ));
  }
}
