/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the waveshield SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx authVerify.example.ts
 */

import { WaveShield } from "waveshield";

const waveShield = new WaveShield({
  security: {
    apiKeyAuth: process.env["WAVESHIELD_API_KEY_AUTH"] ?? "",
    apiSecretAuth: process.env["WAVESHIELD_API_SECRET_AUTH"] ?? "",
  },
});

async function main() {
  const result = await waveShield.auth.verify();

  console.log(result);
}

main().catch(console.error);
