workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    WaveShield API:
        inputs:
            - location: .\openapi.yaml
        overlays:
            - location: .speakeasy\speakeasy-modifications-overlay.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/waveshield/api/wave-shield-api
targets:
    wave-shield:
        target: typescript
        source: WaveShield API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/waveshield/api/wave-shield-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
