/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteV1WebhooksIdRequest = {
  id: string;
};

/** @internal */
export type DeleteV1WebhooksIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteV1WebhooksIdRequest$outboundSchema: z.ZodMiniType<
  DeleteV1WebhooksIdRequest$Outbound,
  DeleteV1WebhooksIdRequest
> = z.object({
  id: z.string(),
});

export function deleteV1WebhooksIdRequestToJSON(
  deleteV1WebhooksIdRequest: DeleteV1WebhooksIdRequest,
): string {
  return JSON.stringify(
    DeleteV1WebhooksIdRequest$outboundSchema.parse(deleteV1WebhooksIdRequest),
  );
}
