/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV1PlayerIdentifierThreatScoreRequest = {
  identifier: string;
};

export const RiskLevel = {
  Low: "LOW",
  Medium: "MEDIUM",
  High: "HIGH",
  Critical: "CRITICAL",
} as const;
export type RiskLevel = OpenEnum<typeof RiskLevel>;

/**
 * Score
 */
export type GetV1PlayerIdentifierThreatScoreResponse = {
  score?: number | undefined;
  riskLevel?: RiskLevel | undefined;
};

/** @internal */
export type GetV1PlayerIdentifierThreatScoreRequest$Outbound = {
  identifier: string;
};

/** @internal */
export const GetV1PlayerIdentifierThreatScoreRequest$outboundSchema:
  z.ZodMiniType<
    GetV1PlayerIdentifierThreatScoreRequest$Outbound,
    GetV1PlayerIdentifierThreatScoreRequest
  > = z.object({
    identifier: z.string(),
  });

export function getV1PlayerIdentifierThreatScoreRequestToJSON(
  getV1PlayerIdentifierThreatScoreRequest:
    GetV1PlayerIdentifierThreatScoreRequest,
): string {
  return JSON.stringify(
    GetV1PlayerIdentifierThreatScoreRequest$outboundSchema.parse(
      getV1PlayerIdentifierThreatScoreRequest,
    ),
  );
}

/** @internal */
export const RiskLevel$inboundSchema: z.ZodMiniType<RiskLevel, unknown> =
  openEnums.inboundSchema(RiskLevel);

/** @internal */
export const GetV1PlayerIdentifierThreatScoreResponse$inboundSchema:
  z.ZodMiniType<GetV1PlayerIdentifierThreatScoreResponse, unknown> = z.object({
    score: types.optional(types.number()),
    riskLevel: types.optional(RiskLevel$inboundSchema),
  });

export function getV1PlayerIdentifierThreatScoreResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1PlayerIdentifierThreatScoreResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1PlayerIdentifierThreatScoreResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1PlayerIdentifierThreatScoreResponse' from JSON`,
  );
}
