/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetV1ServerBansHistoryRequest = {
  limit?: number | undefined;
  page?: number | undefined;
  reason?: string | undefined;
  playerName?: string | undefined;
};

/**
 * Ban history
 */
export type GetV1ServerBansHistoryResponse = {
  data?: Array<models.ServerBanHistory> | undefined;
  pagination?: models.Pagination | undefined;
};

/** @internal */
export type GetV1ServerBansHistoryRequest$Outbound = {
  limit?: number | undefined;
  page?: number | undefined;
  reason?: string | undefined;
  playerName?: string | undefined;
};

/** @internal */
export const GetV1ServerBansHistoryRequest$outboundSchema: z.ZodMiniType<
  GetV1ServerBansHistoryRequest$Outbound,
  GetV1ServerBansHistoryRequest
> = z.object({
  limit: z.optional(z.int()),
  page: z.optional(z.int()),
  reason: z.optional(z.string()),
  playerName: z.optional(z.string()),
});

export function getV1ServerBansHistoryRequestToJSON(
  getV1ServerBansHistoryRequest: GetV1ServerBansHistoryRequest,
): string {
  return JSON.stringify(
    GetV1ServerBansHistoryRequest$outboundSchema.parse(
      getV1ServerBansHistoryRequest,
    ),
  );
}

/** @internal */
export const GetV1ServerBansHistoryResponse$inboundSchema: z.ZodMiniType<
  GetV1ServerBansHistoryResponse,
  unknown
> = z.object({
  data: types.optional(z.array(models.ServerBanHistory$inboundSchema)),
  pagination: types.optional(models.Pagination$inboundSchema),
});

export function getV1ServerBansHistoryResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ServerBansHistoryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ServerBansHistoryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ServerBansHistoryResponse' from JSON`,
  );
}
