/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV1PlayerSearchRequest = {
  name: string;
};

export type Result = {
  id?: string | undefined;
  name?: string | undefined;
  license?: string | undefined;
  server?: string | undefined;
  lastSeen?: Date | undefined;
  playTime?: number | undefined;
};

/**
 * Results
 */
export type GetV1PlayerSearchResponse = {
  results?: Array<Result> | undefined;
};

/** @internal */
export type GetV1PlayerSearchRequest$Outbound = {
  name: string;
};

/** @internal */
export const GetV1PlayerSearchRequest$outboundSchema: z.ZodMiniType<
  GetV1PlayerSearchRequest$Outbound,
  GetV1PlayerSearchRequest
> = z.object({
  name: z.string(),
});

export function getV1PlayerSearchRequestToJSON(
  getV1PlayerSearchRequest: GetV1PlayerSearchRequest,
): string {
  return JSON.stringify(
    GetV1PlayerSearchRequest$outboundSchema.parse(getV1PlayerSearchRequest),
  );
}

/** @internal */
export const Result$inboundSchema: z.ZodMiniType<Result, unknown> = z.object({
  id: types.optional(types.string()),
  name: types.optional(types.string()),
  license: types.optional(types.string()),
  server: types.optional(types.string()),
  lastSeen: types.optional(types.date()),
  playTime: types.optional(types.number()),
});

export function resultFromJSON(
  jsonString: string,
): SafeParseResult<Result, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Result$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Result' from JSON`,
  );
}

/** @internal */
export const GetV1PlayerSearchResponse$inboundSchema: z.ZodMiniType<
  GetV1PlayerSearchResponse,
  unknown
> = z.object({
  results: types.optional(z.array(z.lazy(() => Result$inboundSchema))),
});

export function getV1PlayerSearchResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1PlayerSearchResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1PlayerSearchResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1PlayerSearchResponse' from JSON`,
  );
}
