/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV1ServerBanRequest = {
  /**
   * The unique ban ID
   */
  banId: string;
};

export type GetV1ServerBanDetails = {};

/**
 * Ban details
 */
export type GetV1ServerBanResponse = {
  id?: string | undefined;
  player?: string | undefined;
  reason?: string | undefined;
  details?: GetV1ServerBanDetails | undefined;
  evidence?: string | undefined;
  bannedAt?: Date | undefined;
  expiresAt?: Date | undefined;
  bannedBy?: string | undefined;
  playTime?: number | undefined;
  identifiers?: Array<string> | undefined;
  oldIdentifiers?: Array<string> | undefined;
  oldNames?: Array<string> | undefined;
};

/** @internal */
export type GetV1ServerBanRequest$Outbound = {
  banId: string;
};

/** @internal */
export const GetV1ServerBanRequest$outboundSchema: z.ZodMiniType<
  GetV1ServerBanRequest$Outbound,
  GetV1ServerBanRequest
> = z.object({
  banId: z.string(),
});

export function getV1ServerBanRequestToJSON(
  getV1ServerBanRequest: GetV1ServerBanRequest,
): string {
  return JSON.stringify(
    GetV1ServerBanRequest$outboundSchema.parse(getV1ServerBanRequest),
  );
}

/** @internal */
export const GetV1ServerBanDetails$inboundSchema: z.ZodMiniType<
  GetV1ServerBanDetails,
  unknown
> = z.object({});

export function getV1ServerBanDetailsFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ServerBanDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ServerBanDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ServerBanDetails' from JSON`,
  );
}

/** @internal */
export const GetV1ServerBanResponse$inboundSchema: z.ZodMiniType<
  GetV1ServerBanResponse,
  unknown
> = z.object({
  id: types.optional(types.string()),
  player: types.optional(types.string()),
  reason: types.optional(types.string()),
  details: types.optional(z.lazy(() => GetV1ServerBanDetails$inboundSchema)),
  evidence: types.optional(types.string()),
  bannedAt: types.optional(types.date()),
  expiresAt: types.optional(types.date()),
  bannedBy: types.optional(types.string()),
  playTime: types.optional(types.number()),
  identifiers: types.optional(z.array(types.string())),
  oldIdentifiers: types.optional(z.array(types.string())),
  oldNames: types.optional(z.array(types.string())),
});

export function getV1ServerBanResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ServerBanResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ServerBanResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ServerBanResponse' from JSON`,
  );
}
