/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetV1ServerLogsRequest = {
  limit?: number | undefined;
  type?: string | undefined;
};

/**
 * Logs
 */
export type GetV1ServerLogsResponse = {
  data?: Array<models.ServerLog> | undefined;
  pagination?: models.Pagination | undefined;
};

/** @internal */
export type GetV1ServerLogsRequest$Outbound = {
  limit?: number | undefined;
  type?: string | undefined;
};

/** @internal */
export const GetV1ServerLogsRequest$outboundSchema: z.ZodMiniType<
  GetV1ServerLogsRequest$Outbound,
  GetV1ServerLogsRequest
> = z.object({
  limit: z.optional(z.int()),
  type: z.optional(z.string()),
});

export function getV1ServerLogsRequestToJSON(
  getV1ServerLogsRequest: GetV1ServerLogsRequest,
): string {
  return JSON.stringify(
    GetV1ServerLogsRequest$outboundSchema.parse(getV1ServerLogsRequest),
  );
}

/** @internal */
export const GetV1ServerLogsResponse$inboundSchema: z.ZodMiniType<
  GetV1ServerLogsResponse,
  unknown
> = z.object({
  data: types.optional(z.array(models.ServerLog$inboundSchema)),
  pagination: types.optional(models.Pagination$inboundSchema),
});

export function getV1ServerLogsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ServerLogsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ServerLogsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ServerLogsResponse' from JSON`,
  );
}
