/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const Status = {
  Online: "ONLINE",
  Offline: "OFFLINE",
  Banned: "BANNED",
} as const;
export type Status = OpenEnum<typeof Status>;

export type Info = {
  name?: string | undefined;
  ip?: string | undefined;
  banner?: string | null | undefined;
  version?: string | undefined;
};

export type GetV1ServerStats = {
  currentPlayers?: number | undefined;
  maxSlots?: number | undefined;
  lastSeen?: Date | undefined;
};

export type Subscription = {
  expiresAt?: Date | undefined;
};

/**
 * Server status
 */
export type GetV1ServerResponse = {
  status?: Status | undefined;
  info?: Info | undefined;
  stats?: GetV1ServerStats | undefined;
  subscription?: Subscription | undefined;
};

/** @internal */
export const Status$inboundSchema: z.ZodMiniType<Status, unknown> = openEnums
  .inboundSchema(Status);

/** @internal */
export const Info$inboundSchema: z.ZodMiniType<Info, unknown> = z.object({
  name: types.optional(types.string()),
  ip: types.optional(types.string()),
  banner: z.optional(z.nullable(types.string())),
  version: types.optional(types.string()),
});

export function infoFromJSON(
  jsonString: string,
): SafeParseResult<Info, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Info$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Info' from JSON`,
  );
}

/** @internal */
export const GetV1ServerStats$inboundSchema: z.ZodMiniType<
  GetV1ServerStats,
  unknown
> = z.object({
  currentPlayers: types.optional(types.number()),
  maxSlots: types.optional(types.number()),
  lastSeen: types.optional(types.date()),
});

export function getV1ServerStatsFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ServerStats, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ServerStats$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ServerStats' from JSON`,
  );
}

/** @internal */
export const Subscription$inboundSchema: z.ZodMiniType<Subscription, unknown> =
  z.object({
    expiresAt: types.optional(types.date()),
  });

export function subscriptionFromJSON(
  jsonString: string,
): SafeParseResult<Subscription, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Subscription$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Subscription' from JSON`,
  );
}

/** @internal */
export const GetV1ServerResponse$inboundSchema: z.ZodMiniType<
  GetV1ServerResponse,
  unknown
> = z.object({
  status: types.optional(Status$inboundSchema),
  info: types.optional(z.lazy(() => Info$inboundSchema)),
  stats: types.optional(z.lazy(() => GetV1ServerStats$inboundSchema)),
  subscription: types.optional(z.lazy(() => Subscription$inboundSchema)),
});

export function getV1ServerResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ServerResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ServerResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ServerResponse' from JSON`,
  );
}
