/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Raw config
 */
export type GetV1ServerConfigResponse = {
  config?: { [k: string]: any } | undefined;
};

/** @internal */
export const GetV1ServerConfigResponse$inboundSchema: z.ZodMiniType<
  GetV1ServerConfigResponse,
  unknown
> = z.object({
  config: types.optional(z.record(z.string(), z.any())),
});

export function getV1ServerConfigResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ServerConfigResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ServerConfigResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ServerConfigResponse' from JSON`,
  );
}
