/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Usage = {
  current?: number | undefined;
  limit?: number | undefined;
  remaining?: number | undefined;
  percentage?: number | undefined;
};

export type Period = {
  resetDate?: Date | undefined;
  daysRemaining?: number | undefined;
};

export type Lifetime = {
  totalRequests?: number | undefined;
  lastUsedAt?: Date | undefined;
};

/**
 * Usage details
 */
export type GetV1KeysUsageResponse = {
  usage?: Usage | undefined;
  period?: Period | undefined;
  lifetime?: Lifetime | undefined;
};

/** @internal */
export const Usage$inboundSchema: z.ZodMiniType<Usage, unknown> = z.object({
  current: types.optional(types.number()),
  limit: types.optional(types.number()),
  remaining: types.optional(types.number()),
  percentage: types.optional(types.number()),
});

export function usageFromJSON(
  jsonString: string,
): SafeParseResult<Usage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Usage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Usage' from JSON`,
  );
}

/** @internal */
export const Period$inboundSchema: z.ZodMiniType<Period, unknown> = z.object({
  resetDate: types.optional(types.date()),
  daysRemaining: types.optional(types.number()),
});

export function periodFromJSON(
  jsonString: string,
): SafeParseResult<Period, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Period$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Period' from JSON`,
  );
}

/** @internal */
export const Lifetime$inboundSchema: z.ZodMiniType<Lifetime, unknown> = z
  .object({
    totalRequests: types.optional(types.number()),
    lastUsedAt: types.optional(types.date()),
  });

export function lifetimeFromJSON(
  jsonString: string,
): SafeParseResult<Lifetime, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Lifetime$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Lifetime' from JSON`,
  );
}

/** @internal */
export const GetV1KeysUsageResponse$inboundSchema: z.ZodMiniType<
  GetV1KeysUsageResponse,
  unknown
> = z.object({
  usage: types.optional(z.lazy(() => Usage$inboundSchema)),
  period: types.optional(z.lazy(() => Period$inboundSchema)),
  lifetime: types.optional(z.lazy(() => Lifetime$inboundSchema)),
});

export function getV1KeysUsageResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1KeysUsageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1KeysUsageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1KeysUsageResponse' from JSON`,
  );
}
