/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetV1ServerBansRequest = {
  limit?: number | undefined;
  page?: number | undefined;
  reason?: string | undefined;
  playerName?: string | undefined;
};

/**
 * Active bans
 */
export type GetV1ServerBansResponse = {
  data?: Array<models.BanPublic> | undefined;
  pagination?: models.Pagination | undefined;
};

/** @internal */
export type GetV1ServerBansRequest$Outbound = {
  limit?: number | undefined;
  page?: number | undefined;
  reason?: string | undefined;
  playerName?: string | undefined;
};

/** @internal */
export const GetV1ServerBansRequest$outboundSchema: z.ZodMiniType<
  GetV1ServerBansRequest$Outbound,
  GetV1ServerBansRequest
> = z.object({
  limit: z.optional(z.int()),
  page: z.optional(z.int()),
  reason: z.optional(z.string()),
  playerName: z.optional(z.string()),
});

export function getV1ServerBansRequestToJSON(
  getV1ServerBansRequest: GetV1ServerBansRequest,
): string {
  return JSON.stringify(
    GetV1ServerBansRequest$outboundSchema.parse(getV1ServerBansRequest),
  );
}

/** @internal */
export const GetV1ServerBansResponse$inboundSchema: z.ZodMiniType<
  GetV1ServerBansResponse,
  unknown
> = z.object({
  data: types.optional(z.array(models.BanPublic$inboundSchema)),
  pagination: types.optional(models.Pagination$inboundSchema),
});

export function getV1ServerBansResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ServerBansResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ServerBansResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ServerBansResponse' from JSON`,
  );
}
