/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV1BansStatsRequest = {
  reason?: string | undefined;
};

export type Filter = {
  reason?: string | null | undefined;
};

export type Active = {
  last24h?: number | undefined;
  last7d?: number | undefined;
  last30d?: number | undefined;
  total?: number | undefined;
};

export type Issued = {
  last24h?: number | undefined;
  last7d?: number | undefined;
  last30d?: number | undefined;
  total?: number | undefined;
};

export type GetV1BansStatsStats = {
  active?: Active | undefined;
  issued?: Issued | undefined;
};

/**
 * Statistics
 */
export type GetV1BansStatsResponse = {
  filter?: Filter | undefined;
  stats?: GetV1BansStatsStats | undefined;
};

/** @internal */
export type GetV1BansStatsRequest$Outbound = {
  reason?: string | undefined;
};

/** @internal */
export const GetV1BansStatsRequest$outboundSchema: z.ZodMiniType<
  GetV1BansStatsRequest$Outbound,
  GetV1BansStatsRequest
> = z.object({
  reason: z.optional(z.string()),
});

export function getV1BansStatsRequestToJSON(
  getV1BansStatsRequest: GetV1BansStatsRequest,
): string {
  return JSON.stringify(
    GetV1BansStatsRequest$outboundSchema.parse(getV1BansStatsRequest),
  );
}

/** @internal */
export const Filter$inboundSchema: z.ZodMiniType<Filter, unknown> = z.object({
  reason: z.optional(z.nullable(types.string())),
});

export function filterFromJSON(
  jsonString: string,
): SafeParseResult<Filter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Filter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Filter' from JSON`,
  );
}

/** @internal */
export const Active$inboundSchema: z.ZodMiniType<Active, unknown> = z.object({
  last24h: types.optional(types.number()),
  last7d: types.optional(types.number()),
  last30d: types.optional(types.number()),
  total: types.optional(types.number()),
});

export function activeFromJSON(
  jsonString: string,
): SafeParseResult<Active, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Active$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Active' from JSON`,
  );
}

/** @internal */
export const Issued$inboundSchema: z.ZodMiniType<Issued, unknown> = z.object({
  last24h: types.optional(types.number()),
  last7d: types.optional(types.number()),
  last30d: types.optional(types.number()),
  total: types.optional(types.number()),
});

export function issuedFromJSON(
  jsonString: string,
): SafeParseResult<Issued, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Issued$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Issued' from JSON`,
  );
}

/** @internal */
export const GetV1BansStatsStats$inboundSchema: z.ZodMiniType<
  GetV1BansStatsStats,
  unknown
> = z.object({
  active: types.optional(z.lazy(() => Active$inboundSchema)),
  issued: types.optional(z.lazy(() => Issued$inboundSchema)),
});

export function getV1BansStatsStatsFromJSON(
  jsonString: string,
): SafeParseResult<GetV1BansStatsStats, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1BansStatsStats$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1BansStatsStats' from JSON`,
  );
}

/** @internal */
export const GetV1BansStatsResponse$inboundSchema: z.ZodMiniType<
  GetV1BansStatsResponse,
  unknown
> = z.object({
  filter: types.optional(z.lazy(() => Filter$inboundSchema)),
  stats: types.optional(z.lazy(() => GetV1BansStatsStats$inboundSchema)),
});

export function getV1BansStatsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1BansStatsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1BansStatsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1BansStatsResponse' from JSON`,
  );
}
