/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV1PlayerIdentifierRequest = {
  identifier: string;
};

export type GetV1PlayerIdentifierStats = {
  globalPlayTime?: number | undefined;
  serversVisited?: number | undefined;
  firstSeen?: Date | undefined;
  lastSeen?: Date | undefined;
  lastServerJoined?: string | undefined;
};

export type Bans = {
  activeBans?: number | undefined;
  totalBans?: number | undefined;
};

/**
 * Profile
 */
export type GetV1PlayerIdentifierResponse = {
  name?: string | undefined;
  license?: string | undefined;
  stats?: GetV1PlayerIdentifierStats | undefined;
  bans?: Bans | undefined;
};

/** @internal */
export type GetV1PlayerIdentifierRequest$Outbound = {
  identifier: string;
};

/** @internal */
export const GetV1PlayerIdentifierRequest$outboundSchema: z.ZodMiniType<
  GetV1PlayerIdentifierRequest$Outbound,
  GetV1PlayerIdentifierRequest
> = z.object({
  identifier: z.string(),
});

export function getV1PlayerIdentifierRequestToJSON(
  getV1PlayerIdentifierRequest: GetV1PlayerIdentifierRequest,
): string {
  return JSON.stringify(
    GetV1PlayerIdentifierRequest$outboundSchema.parse(
      getV1PlayerIdentifierRequest,
    ),
  );
}

/** @internal */
export const GetV1PlayerIdentifierStats$inboundSchema: z.ZodMiniType<
  GetV1PlayerIdentifierStats,
  unknown
> = z.object({
  globalPlayTime: types.optional(types.number()),
  serversVisited: types.optional(types.number()),
  firstSeen: types.optional(types.date()),
  lastSeen: types.optional(types.date()),
  lastServerJoined: types.optional(types.string()),
});

export function getV1PlayerIdentifierStatsFromJSON(
  jsonString: string,
): SafeParseResult<GetV1PlayerIdentifierStats, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1PlayerIdentifierStats$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1PlayerIdentifierStats' from JSON`,
  );
}

/** @internal */
export const Bans$inboundSchema: z.ZodMiniType<Bans, unknown> = z.object({
  activeBans: types.optional(types.number()),
  totalBans: types.optional(types.number()),
});

export function bansFromJSON(
  jsonString: string,
): SafeParseResult<Bans, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Bans$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Bans' from JSON`,
  );
}

/** @internal */
export const GetV1PlayerIdentifierResponse$inboundSchema: z.ZodMiniType<
  GetV1PlayerIdentifierResponse,
  unknown
> = z.object({
  name: types.optional(types.string()),
  license: types.optional(types.string()),
  stats: types.optional(z.lazy(() => GetV1PlayerIdentifierStats$inboundSchema)),
  bans: types.optional(z.lazy(() => Bans$inboundSchema)),
});

export function getV1PlayerIdentifierResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1PlayerIdentifierResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1PlayerIdentifierResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1PlayerIdentifierResponse' from JSON`,
  );
}
