/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetV1PlayerIdentifierAnalysisRequest = {
  identifier: string;
};

/** @internal */
export type GetV1PlayerIdentifierAnalysisRequest$Outbound = {
  identifier: string;
};

/** @internal */
export const GetV1PlayerIdentifierAnalysisRequest$outboundSchema: z.ZodMiniType<
  GetV1PlayerIdentifierAnalysisRequest$Outbound,
  GetV1PlayerIdentifierAnalysisRequest
> = z.object({
  identifier: z.string(),
});

export function getV1PlayerIdentifierAnalysisRequestToJSON(
  getV1PlayerIdentifierAnalysisRequest: GetV1PlayerIdentifierAnalysisRequest,
): string {
  return JSON.stringify(
    GetV1PlayerIdentifierAnalysisRequest$outboundSchema.parse(
      getV1PlayerIdentifierAnalysisRequest,
    ),
  );
}
