/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetV1BansSearchRequest = {
  limit?: number | undefined;
  page?: number | undefined;
  reason?: string | undefined;
  playerName?: string | undefined;
};

/**
 * Search results
 */
export type GetV1BansSearchResponse = {
  data?: Array<models.BanPublic> | undefined;
  pagination?: models.Pagination | undefined;
};

/** @internal */
export type GetV1BansSearchRequest$Outbound = {
  limit?: number | undefined;
  page?: number | undefined;
  reason?: string | undefined;
  playerName?: string | undefined;
};

/** @internal */
export const GetV1BansSearchRequest$outboundSchema: z.ZodMiniType<
  GetV1BansSearchRequest$Outbound,
  GetV1BansSearchRequest
> = z.object({
  limit: z.optional(z.int()),
  page: z.optional(z.int()),
  reason: z.optional(z.string()),
  playerName: z.optional(z.string()),
});

export function getV1BansSearchRequestToJSON(
  getV1BansSearchRequest: GetV1BansSearchRequest,
): string {
  return JSON.stringify(
    GetV1BansSearchRequest$outboundSchema.parse(getV1BansSearchRequest),
  );
}

/** @internal */
export const GetV1BansSearchResponse$inboundSchema: z.ZodMiniType<
  GetV1BansSearchResponse,
  unknown
> = z.object({
  data: types.optional(z.array(models.BanPublic$inboundSchema)),
  pagination: types.optional(models.Pagination$inboundSchema),
});

export function getV1BansSearchResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1BansSearchResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1BansSearchResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1BansSearchResponse' from JSON`,
  );
}
