/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const Window = {
  TwentyFourh: "24h",
  Sevend: "7d",
  Thirtyd: "30d",
} as const;
export type Window = ClosedEnum<typeof Window>;

export type GetV1BansTrendsRequest = {
  window?: Window | undefined;
};

export type Trend = {
  reason?: string | undefined;
  count?: number | undefined;
};

/**
 * Trends
 */
export type GetV1BansTrendsResponse = {
  window?: string | undefined;
  since?: string | undefined;
  trends?: Array<Trend> | undefined;
};

/** @internal */
export const Window$outboundSchema: z.ZodMiniEnum<typeof Window> = z.enum(
  Window,
);

/** @internal */
export type GetV1BansTrendsRequest$Outbound = {
  window?: string | undefined;
};

/** @internal */
export const GetV1BansTrendsRequest$outboundSchema: z.ZodMiniType<
  GetV1BansTrendsRequest$Outbound,
  GetV1BansTrendsRequest
> = z.object({
  window: z.optional(Window$outboundSchema),
});

export function getV1BansTrendsRequestToJSON(
  getV1BansTrendsRequest: GetV1BansTrendsRequest,
): string {
  return JSON.stringify(
    GetV1BansTrendsRequest$outboundSchema.parse(getV1BansTrendsRequest),
  );
}

/** @internal */
export const Trend$inboundSchema: z.ZodMiniType<Trend, unknown> = z.object({
  reason: types.optional(types.string()),
  count: types.optional(types.number()),
});

export function trendFromJSON(
  jsonString: string,
): SafeParseResult<Trend, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Trend$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Trend' from JSON`,
  );
}

/** @internal */
export const GetV1BansTrendsResponse$inboundSchema: z.ZodMiniType<
  GetV1BansTrendsResponse,
  unknown
> = z.object({
  window: types.optional(types.string()),
  since: types.optional(types.string()),
  trends: types.optional(z.array(z.lazy(() => Trend$inboundSchema))),
});

export function getV1BansTrendsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1BansTrendsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1BansTrendsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1BansTrendsResponse' from JSON`,
  );
}
