/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV1PlayerIdentifierServersRequest = {
  identifier: string;
};

export type GetV1PlayerIdentifierServersServer = {
  id?: string | undefined;
  name?: string | undefined;
  firstJoin?: Date | undefined;
  lastJoin?: Date | undefined;
  playTime?: number | undefined;
};

/**
 * History
 */
export type GetV1PlayerIdentifierServersResponse = {
  servers?: Array<GetV1PlayerIdentifierServersServer> | undefined;
};

/** @internal */
export type GetV1PlayerIdentifierServersRequest$Outbound = {
  identifier: string;
};

/** @internal */
export const GetV1PlayerIdentifierServersRequest$outboundSchema: z.ZodMiniType<
  GetV1PlayerIdentifierServersRequest$Outbound,
  GetV1PlayerIdentifierServersRequest
> = z.object({
  identifier: z.string(),
});

export function getV1PlayerIdentifierServersRequestToJSON(
  getV1PlayerIdentifierServersRequest: GetV1PlayerIdentifierServersRequest,
): string {
  return JSON.stringify(
    GetV1PlayerIdentifierServersRequest$outboundSchema.parse(
      getV1PlayerIdentifierServersRequest,
    ),
  );
}

/** @internal */
export const GetV1PlayerIdentifierServersServer$inboundSchema: z.ZodMiniType<
  GetV1PlayerIdentifierServersServer,
  unknown
> = z.object({
  id: types.optional(types.string()),
  name: types.optional(types.string()),
  firstJoin: types.optional(types.date()),
  lastJoin: types.optional(types.date()),
  playTime: types.optional(types.number()),
});

export function getV1PlayerIdentifierServersServerFromJSON(
  jsonString: string,
): SafeParseResult<GetV1PlayerIdentifierServersServer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1PlayerIdentifierServersServer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1PlayerIdentifierServersServer' from JSON`,
  );
}

/** @internal */
export const GetV1PlayerIdentifierServersResponse$inboundSchema: z.ZodMiniType<
  GetV1PlayerIdentifierServersResponse,
  unknown
> = z.object({
  servers: types.optional(
    z.array(z.lazy(() => GetV1PlayerIdentifierServersServer$inboundSchema)),
  ),
});

export function getV1PlayerIdentifierServersResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1PlayerIdentifierServersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1PlayerIdentifierServersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1PlayerIdentifierServersResponse' from JSON`,
  );
}
