/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV1ServerStatsRequest = {
  window?: string | undefined;
};

export type Current = {
  players?: number | undefined;
  online?: boolean | undefined;
};

export type Averages = {
  players?: number | undefined;
};

export type Activity = {
  bansIssued?: number | undefined;
  newBans?: number | undefined;
  newPlayers?: number | undefined;
  playerJoins?: number | undefined;
};

export type History = {
  timestamp?: string | undefined;
  players?: number | undefined;
  bans?: number | undefined;
};

/**
 * Historical metrics
 */
export type GetV1ServerStatsResponse = {
  window?: string | undefined;
  since?: string | undefined;
  current?: Current | undefined;
  averages?: Averages | undefined;
  activity?: Activity | undefined;
  history?: Array<History> | undefined;
};

/** @internal */
export type GetV1ServerStatsRequest$Outbound = {
  window: string;
};

/** @internal */
export const GetV1ServerStatsRequest$outboundSchema: z.ZodMiniType<
  GetV1ServerStatsRequest$Outbound,
  GetV1ServerStatsRequest
> = z.object({
  window: z._default(z.string(), "24h"),
});

export function getV1ServerStatsRequestToJSON(
  getV1ServerStatsRequest: GetV1ServerStatsRequest,
): string {
  return JSON.stringify(
    GetV1ServerStatsRequest$outboundSchema.parse(getV1ServerStatsRequest),
  );
}

/** @internal */
export const Current$inboundSchema: z.ZodMiniType<Current, unknown> = z.object({
  players: types.optional(types.number()),
  online: types.optional(types.boolean()),
});

export function currentFromJSON(
  jsonString: string,
): SafeParseResult<Current, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Current$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Current' from JSON`,
  );
}

/** @internal */
export const Averages$inboundSchema: z.ZodMiniType<Averages, unknown> = z
  .object({
    players: types.optional(types.number()),
  });

export function averagesFromJSON(
  jsonString: string,
): SafeParseResult<Averages, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Averages$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Averages' from JSON`,
  );
}

/** @internal */
export const Activity$inboundSchema: z.ZodMiniType<Activity, unknown> = z
  .object({
    bansIssued: types.optional(types.number()),
    newBans: types.optional(types.number()),
    newPlayers: types.optional(types.number()),
    playerJoins: types.optional(types.number()),
  });

export function activityFromJSON(
  jsonString: string,
): SafeParseResult<Activity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Activity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Activity' from JSON`,
  );
}

/** @internal */
export const History$inboundSchema: z.ZodMiniType<History, unknown> = z.object({
  timestamp: types.optional(types.string()),
  players: types.optional(types.number()),
  bans: types.optional(types.number()),
});

export function historyFromJSON(
  jsonString: string,
): SafeParseResult<History, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => History$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'History' from JSON`,
  );
}

/** @internal */
export const GetV1ServerStatsResponse$inboundSchema: z.ZodMiniType<
  GetV1ServerStatsResponse,
  unknown
> = z.object({
  window: types.optional(types.string()),
  since: types.optional(types.string()),
  current: types.optional(z.lazy(() => Current$inboundSchema)),
  averages: types.optional(z.lazy(() => Averages$inboundSchema)),
  activity: types.optional(z.lazy(() => Activity$inboundSchema)),
  history: types.optional(z.array(z.lazy(() => History$inboundSchema))),
});

export function getV1ServerStatsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ServerStatsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ServerStatsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ServerStatsResponse' from JSON`,
  );
}
