/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetV1PlayerIdentifierBansRequest = {
  identifier: string;
};

/**
 * Active bans
 */
export type GetV1PlayerIdentifierBansResponse = {
  count?: number | undefined;
  bans?: Array<models.BanPublic> | undefined;
};

/** @internal */
export type GetV1PlayerIdentifierBansRequest$Outbound = {
  identifier: string;
};

/** @internal */
export const GetV1PlayerIdentifierBansRequest$outboundSchema: z.ZodMiniType<
  GetV1PlayerIdentifierBansRequest$Outbound,
  GetV1PlayerIdentifierBansRequest
> = z.object({
  identifier: z.string(),
});

export function getV1PlayerIdentifierBansRequestToJSON(
  getV1PlayerIdentifierBansRequest: GetV1PlayerIdentifierBansRequest,
): string {
  return JSON.stringify(
    GetV1PlayerIdentifierBansRequest$outboundSchema.parse(
      getV1PlayerIdentifierBansRequest,
    ),
  );
}

/** @internal */
export const GetV1PlayerIdentifierBansResponse$inboundSchema: z.ZodMiniType<
  GetV1PlayerIdentifierBansResponse,
  unknown
> = z.object({
  count: types.optional(types.number()),
  bans: types.optional(z.array(models.BanPublic$inboundSchema)),
});

export function getV1PlayerIdentifierBansResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1PlayerIdentifierBansResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1PlayerIdentifierBansResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1PlayerIdentifierBansResponse' from JSON`,
  );
}
