/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetV1PlayerIdentifierBansHistoryRequest = {
  identifier: string;
};

/**
 * Ban history
 */
export type GetV1PlayerIdentifierBansHistoryResponse = {
  count?: number | undefined;
  bans?: Array<models.ServerBanHistory> | undefined;
};

/** @internal */
export type GetV1PlayerIdentifierBansHistoryRequest$Outbound = {
  identifier: string;
};

/** @internal */
export const GetV1PlayerIdentifierBansHistoryRequest$outboundSchema:
  z.ZodMiniType<
    GetV1PlayerIdentifierBansHistoryRequest$Outbound,
    GetV1PlayerIdentifierBansHistoryRequest
  > = z.object({
    identifier: z.string(),
  });

export function getV1PlayerIdentifierBansHistoryRequestToJSON(
  getV1PlayerIdentifierBansHistoryRequest:
    GetV1PlayerIdentifierBansHistoryRequest,
): string {
  return JSON.stringify(
    GetV1PlayerIdentifierBansHistoryRequest$outboundSchema.parse(
      getV1PlayerIdentifierBansHistoryRequest,
    ),
  );
}

/** @internal */
export const GetV1PlayerIdentifierBansHistoryResponse$inboundSchema:
  z.ZodMiniType<GetV1PlayerIdentifierBansHistoryResponse, unknown> = z.object({
    count: types.optional(types.number()),
    bans: types.optional(z.array(models.ServerBanHistory$inboundSchema)),
  });

export function getV1PlayerIdentifierBansHistoryResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1PlayerIdentifierBansHistoryResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1PlayerIdentifierBansHistoryResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1PlayerIdentifierBansHistoryResponse' from JSON`,
  );
}
