/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Admin = {
  discordId?: string | undefined;
  permissions?: Array<string> | undefined;
  addedAt?: Date | undefined;
};

/**
 * Admins list
 */
export type GetV1ServerAdminsResponse = {
  count?: number | undefined;
  admins?: Array<Admin> | undefined;
};

/** @internal */
export const Admin$inboundSchema: z.ZodMiniType<Admin, unknown> = z.object({
  discordId: types.optional(types.string()),
  permissions: types.optional(z.array(types.string())),
  addedAt: types.optional(types.date()),
});

export function adminFromJSON(
  jsonString: string,
): SafeParseResult<Admin, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Admin$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Admin' from JSON`,
  );
}

/** @internal */
export const GetV1ServerAdminsResponse$inboundSchema: z.ZodMiniType<
  GetV1ServerAdminsResponse,
  unknown
> = z.object({
  count: types.optional(types.number()),
  admins: types.optional(z.array(z.lazy(() => Admin$inboundSchema))),
});

export function getV1ServerAdminsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ServerAdminsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ServerAdminsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ServerAdminsResponse' from JSON`,
  );
}
