/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetV1BansRecentRequest = {
  limit?: number | undefined;
};

export type GetV1BansRecentMeta = {
  count?: number | undefined;
  limit?: number | undefined;
};

/**
 * List of recent bans
 */
export type GetV1BansRecentResponse = {
  data?: Array<models.BanPublic> | undefined;
  meta?: GetV1BansRecentMeta | undefined;
};

/** @internal */
export type GetV1BansRecentRequest$Outbound = {
  limit: number;
};

/** @internal */
export const GetV1BansRecentRequest$outboundSchema: z.ZodMiniType<
  GetV1BansRecentRequest$Outbound,
  GetV1BansRecentRequest
> = z.object({
  limit: z._default(z.int(), 10),
});

export function getV1BansRecentRequestToJSON(
  getV1BansRecentRequest: GetV1BansRecentRequest,
): string {
  return JSON.stringify(
    GetV1BansRecentRequest$outboundSchema.parse(getV1BansRecentRequest),
  );
}

/** @internal */
export const GetV1BansRecentMeta$inboundSchema: z.ZodMiniType<
  GetV1BansRecentMeta,
  unknown
> = z.object({
  count: types.optional(types.number()),
  limit: types.optional(types.number()),
});

export function getV1BansRecentMetaFromJSON(
  jsonString: string,
): SafeParseResult<GetV1BansRecentMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1BansRecentMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1BansRecentMeta' from JSON`,
  );
}

/** @internal */
export const GetV1BansRecentResponse$inboundSchema: z.ZodMiniType<
  GetV1BansRecentResponse,
  unknown
> = z.object({
  data: types.optional(z.array(models.BanPublic$inboundSchema)),
  meta: types.optional(z.lazy(() => GetV1BansRecentMeta$inboundSchema)),
});

export function getV1BansRecentResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1BansRecentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1BansRecentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1BansRecentResponse' from JSON`,
  );
}
