/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Connected players
 */
export type GetV1ServerPlayersResponse = {
  count?: number | undefined;
  players?: Array<{ [k: string]: any }> | undefined;
};

/** @internal */
export const GetV1ServerPlayersResponse$inboundSchema: z.ZodMiniType<
  GetV1ServerPlayersResponse,
  unknown
> = z.object({
  count: types.optional(types.number()),
  players: types.optional(z.array(z.record(z.string(), z.any()))),
});

export function getV1ServerPlayersResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ServerPlayersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ServerPlayersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ServerPlayersResponse' from JSON`,
  );
}
