/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV1PlayerIdentifierDiscordLookupRequest = {
  identifier: string;
};

export type Role = {
  roleId?: string | undefined;
  roleName?: string | undefined;
  roleColor?: string | undefined;
};

export type GetV1PlayerIdentifierDiscordLookupServer = {
  serverName?: string | undefined;
  serverGuildId?: string | undefined;
  serverIconUrl?: string | undefined;
  roles?: Array<Role> | undefined;
};

/**
 * Discord lookup result
 */
export type GetV1PlayerIdentifierDiscordLookupResponse = {
  discordId?: string | undefined;
  servers?: Array<GetV1PlayerIdentifierDiscordLookupServer> | undefined;
  totalServers?: number | undefined;
  isInCheatServer?: boolean | undefined;
};

/** @internal */
export type GetV1PlayerIdentifierDiscordLookupRequest$Outbound = {
  identifier: string;
};

/** @internal */
export const GetV1PlayerIdentifierDiscordLookupRequest$outboundSchema:
  z.ZodMiniType<
    GetV1PlayerIdentifierDiscordLookupRequest$Outbound,
    GetV1PlayerIdentifierDiscordLookupRequest
  > = z.object({
    identifier: z.string(),
  });

export function getV1PlayerIdentifierDiscordLookupRequestToJSON(
  getV1PlayerIdentifierDiscordLookupRequest:
    GetV1PlayerIdentifierDiscordLookupRequest,
): string {
  return JSON.stringify(
    GetV1PlayerIdentifierDiscordLookupRequest$outboundSchema.parse(
      getV1PlayerIdentifierDiscordLookupRequest,
    ),
  );
}

/** @internal */
export const Role$inboundSchema: z.ZodMiniType<Role, unknown> = z.object({
  roleId: types.optional(types.string()),
  roleName: types.optional(types.string()),
  roleColor: types.optional(types.string()),
});

export function roleFromJSON(
  jsonString: string,
): SafeParseResult<Role, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Role$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Role' from JSON`,
  );
}

/** @internal */
export const GetV1PlayerIdentifierDiscordLookupServer$inboundSchema:
  z.ZodMiniType<GetV1PlayerIdentifierDiscordLookupServer, unknown> = z.object({
    serverName: types.optional(types.string()),
    serverGuildId: types.optional(types.string()),
    serverIconUrl: types.optional(types.string()),
    roles: types.optional(z.array(z.lazy(() => Role$inboundSchema))),
  });

export function getV1PlayerIdentifierDiscordLookupServerFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1PlayerIdentifierDiscordLookupServer,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1PlayerIdentifierDiscordLookupServer$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1PlayerIdentifierDiscordLookupServer' from JSON`,
  );
}

/** @internal */
export const GetV1PlayerIdentifierDiscordLookupResponse$inboundSchema:
  z.ZodMiniType<GetV1PlayerIdentifierDiscordLookupResponse, unknown> = z.object(
    {
      discordId: types.optional(types.string()),
      servers: types.optional(z.array(z.lazy(() =>
        GetV1PlayerIdentifierDiscordLookupServer$inboundSchema
      ))),
      totalServers: types.optional(types.number()),
      isInCheatServer: types.optional(types.boolean()),
    },
  );

export function getV1PlayerIdentifierDiscordLookupResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1PlayerIdentifierDiscordLookupResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1PlayerIdentifierDiscordLookupResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1PlayerIdentifierDiscordLookupResponse' from JSON`,
  );
}
