/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Servers = {
  total?: number | undefined;
  online?: number | undefined;
};

export type Players = {
  trackedTotal?: number | undefined;
  online?: number | undefined;
  bannedTotal?: number | undefined;
};

export type Identifiers = {
  trackedTotal?: number | undefined;
  bannedTotal?: number | undefined;
};

export type System = {
  version?: string | undefined;
  bansIssued?: number | undefined;
  lastUpdate?: string | undefined;
};

/**
 * Platform statistics
 */
export type GetV1StatsResponse = {
  servers?: Servers | undefined;
  players?: Players | undefined;
  identifiers?: Identifiers | undefined;
  system?: System | undefined;
};

/** @internal */
export const Servers$inboundSchema: z.ZodMiniType<Servers, unknown> = z.object({
  total: types.optional(types.number()),
  online: types.optional(types.number()),
});

export function serversFromJSON(
  jsonString: string,
): SafeParseResult<Servers, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Servers$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Servers' from JSON`,
  );
}

/** @internal */
export const Players$inboundSchema: z.ZodMiniType<Players, unknown> = z.pipe(
  z.object({
    tracked_total: types.optional(types.number()),
    online: types.optional(types.number()),
    banned_total: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "tracked_total": "trackedTotal",
      "banned_total": "bannedTotal",
    });
  }),
);

export function playersFromJSON(
  jsonString: string,
): SafeParseResult<Players, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Players$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Players' from JSON`,
  );
}

/** @internal */
export const Identifiers$inboundSchema: z.ZodMiniType<Identifiers, unknown> = z
  .pipe(
    z.object({
      tracked_total: types.optional(types.number()),
      banned_total: types.optional(types.number()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "tracked_total": "trackedTotal",
        "banned_total": "bannedTotal",
      });
    }),
  );

export function identifiersFromJSON(
  jsonString: string,
): SafeParseResult<Identifiers, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Identifiers$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Identifiers' from JSON`,
  );
}

/** @internal */
export const System$inboundSchema: z.ZodMiniType<System, unknown> = z.pipe(
  z.object({
    version: types.optional(types.string()),
    bans_issued: types.optional(types.number()),
    last_update: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "bans_issued": "bansIssued",
      "last_update": "lastUpdate",
    });
  }),
);

export function systemFromJSON(
  jsonString: string,
): SafeParseResult<System, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => System$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'System' from JSON`,
  );
}

/** @internal */
export const GetV1StatsResponse$inboundSchema: z.ZodMiniType<
  GetV1StatsResponse,
  unknown
> = z.object({
  servers: types.optional(z.lazy(() => Servers$inboundSchema)),
  players: types.optional(z.lazy(() => Players$inboundSchema)),
  identifiers: types.optional(z.lazy(() => Identifiers$inboundSchema)),
  system: types.optional(z.lazy(() => System$inboundSchema)),
});

export function getV1StatsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1StatsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1StatsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1StatsResponse' from JSON`,
  );
}
