/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Key = {
  id?: string | undefined;
  name?: string | undefined;
  tier?: string | undefined;
  status?: string | undefined;
  createdAt?: Date | undefined;
  expiresAt?: Date | undefined;
};

export type Permissions = {};

export type RateLimit = {
  limit?: number | undefined;
};

export type PostV1AuthVerifyMeta = {
  requestId?: string | undefined;
  timestamp?: string | undefined;
};

/**
 * Credentials Valid
 */
export type PostV1AuthVerifyResponse = {
  valid?: boolean | undefined;
  key?: Key | undefined;
  permissions?: Permissions | undefined;
  rateLimit?: RateLimit | undefined;
  meta?: PostV1AuthVerifyMeta | undefined;
};

/** @internal */
export const Key$inboundSchema: z.ZodMiniType<Key, unknown> = z.object({
  id: types.optional(types.string()),
  name: types.optional(types.string()),
  tier: types.optional(types.string()),
  status: types.optional(types.string()),
  createdAt: types.optional(types.date()),
  expiresAt: types.optional(types.date()),
});

export function keyFromJSON(
  jsonString: string,
): SafeParseResult<Key, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Key$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Key' from JSON`,
  );
}

/** @internal */
export const Permissions$inboundSchema: z.ZodMiniType<Permissions, unknown> = z
  .object({});

export function permissionsFromJSON(
  jsonString: string,
): SafeParseResult<Permissions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Permissions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Permissions' from JSON`,
  );
}

/** @internal */
export const RateLimit$inboundSchema: z.ZodMiniType<RateLimit, unknown> = z
  .object({
    limit: types.optional(types.number()),
  });

export function rateLimitFromJSON(
  jsonString: string,
): SafeParseResult<RateLimit, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RateLimit$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RateLimit' from JSON`,
  );
}

/** @internal */
export const PostV1AuthVerifyMeta$inboundSchema: z.ZodMiniType<
  PostV1AuthVerifyMeta,
  unknown
> = z.object({
  requestId: types.optional(types.string()),
  timestamp: types.optional(types.string()),
});

export function postV1AuthVerifyMetaFromJSON(
  jsonString: string,
): SafeParseResult<PostV1AuthVerifyMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1AuthVerifyMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1AuthVerifyMeta' from JSON`,
  );
}

/** @internal */
export const PostV1AuthVerifyResponse$inboundSchema: z.ZodMiniType<
  PostV1AuthVerifyResponse,
  unknown
> = z.object({
  valid: types.optional(types.boolean()),
  key: types.optional(z.lazy(() => Key$inboundSchema)),
  permissions: types.optional(z.lazy(() => Permissions$inboundSchema)),
  rateLimit: types.optional(z.lazy(() => RateLimit$inboundSchema)),
  meta: types.optional(z.lazy(() => PostV1AuthVerifyMeta$inboundSchema)),
});

export function postV1AuthVerifyResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1AuthVerifyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1AuthVerifyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1AuthVerifyResponse' from JSON`,
  );
}
