/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const Permission = {
  All: "ALL",
  Configuration: "CONFIGURATION",
  DownloadFiles: "DOWNLOAD_FILES",
  ManageAdmins: "MANAGE_ADMINS",
  UnbanAll: "UNBAN_ALL",
  ManageBans: "MANAGE_BANS",
  ManageRules: "MANAGE_RULES",
  PlayersLookup: "PLAYERS_LOOKUP",
  PlayersKick: "PLAYERS_KICK",
  ViewLogs: "VIEW_LOGS",
  ViewConsole: "VIEW_CONSOLE",
  RunCommands: "RUN_COMMANDS",
  Bypass: "BYPASS",
} as const;
export type Permission = ClosedEnum<typeof Permission>;

export type PostV1ServerAdminAddRequest = {
  discordId: string;
  permissions: Array<Permission>;
};

export type Member = {};

/**
 * Success
 */
export type PostV1ServerAdminAddResponse = {
  success?: boolean | undefined;
  member?: Member | undefined;
};

/** @internal */
export const Permission$outboundSchema: z.ZodMiniEnum<typeof Permission> = z
  .enum(Permission);

/** @internal */
export type PostV1ServerAdminAddRequest$Outbound = {
  discordId: string;
  permissions: Array<string>;
};

/** @internal */
export const PostV1ServerAdminAddRequest$outboundSchema: z.ZodMiniType<
  PostV1ServerAdminAddRequest$Outbound,
  PostV1ServerAdminAddRequest
> = z.object({
  discordId: z.string(),
  permissions: z.array(Permission$outboundSchema),
});

export function postV1ServerAdminAddRequestToJSON(
  postV1ServerAdminAddRequest: PostV1ServerAdminAddRequest,
): string {
  return JSON.stringify(
    PostV1ServerAdminAddRequest$outboundSchema.parse(
      postV1ServerAdminAddRequest,
    ),
  );
}

/** @internal */
export const Member$inboundSchema: z.ZodMiniType<Member, unknown> = z.object(
  {},
);

export function memberFromJSON(
  jsonString: string,
): SafeParseResult<Member, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Member$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Member' from JSON`,
  );
}

/** @internal */
export const PostV1ServerAdminAddResponse$inboundSchema: z.ZodMiniType<
  PostV1ServerAdminAddResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  member: types.optional(z.lazy(() => Member$inboundSchema)),
});

export function postV1ServerAdminAddResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1ServerAdminAddResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1ServerAdminAddResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1ServerAdminAddResponse' from JSON`,
  );
}
