/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostV1ServerUnbanRequest = {
  banId: string;
};

/**
 * Success
 */
export type PostV1ServerUnbanResponse = {
  success?: boolean | undefined;
  message?: string | undefined;
};

/** @internal */
export type PostV1ServerUnbanRequest$Outbound = {
  banId: string;
};

/** @internal */
export const PostV1ServerUnbanRequest$outboundSchema: z.ZodMiniType<
  PostV1ServerUnbanRequest$Outbound,
  PostV1ServerUnbanRequest
> = z.object({
  banId: z.string(),
});

export function postV1ServerUnbanRequestToJSON(
  postV1ServerUnbanRequest: PostV1ServerUnbanRequest,
): string {
  return JSON.stringify(
    PostV1ServerUnbanRequest$outboundSchema.parse(postV1ServerUnbanRequest),
  );
}

/** @internal */
export const PostV1ServerUnbanResponse$inboundSchema: z.ZodMiniType<
  PostV1ServerUnbanResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  message: types.optional(types.string()),
});

export function postV1ServerUnbanResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1ServerUnbanResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1ServerUnbanResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1ServerUnbanResponse' from JSON`,
  );
}
