/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostV1ServerKickRequest = {
  playerId: string;
  reason?: string | undefined;
  by?: string | undefined;
};

/**
 * Success
 */
export type PostV1ServerKickResponse = {
  success?: boolean | undefined;
  message?: string | undefined;
};

/** @internal */
export type PostV1ServerKickRequest$Outbound = {
  playerId: string;
  reason?: string | undefined;
  by?: string | undefined;
};

/** @internal */
export const PostV1ServerKickRequest$outboundSchema: z.ZodMiniType<
  PostV1ServerKickRequest$Outbound,
  PostV1ServerKickRequest
> = z.object({
  playerId: z.string(),
  reason: z.optional(z.string()),
  by: z.optional(z.string()),
});

export function postV1ServerKickRequestToJSON(
  postV1ServerKickRequest: PostV1ServerKickRequest,
): string {
  return JSON.stringify(
    PostV1ServerKickRequest$outboundSchema.parse(postV1ServerKickRequest),
  );
}

/** @internal */
export const PostV1ServerKickResponse$inboundSchema: z.ZodMiniType<
  PostV1ServerKickResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  message: types.optional(types.string()),
});

export function postV1ServerKickResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1ServerKickResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1ServerKickResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1ServerKickResponse' from JSON`,
  );
}
