/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostV1ServerScreenshotRequest = {
  playerId: string;
};

/**
 * Success
 */
export type PostV1ServerScreenshotResponse = {
  success?: boolean | undefined;
  screenshotUrl?: string | undefined;
};

/** @internal */
export type PostV1ServerScreenshotRequest$Outbound = {
  playerId: string;
};

/** @internal */
export const PostV1ServerScreenshotRequest$outboundSchema: z.ZodMiniType<
  PostV1ServerScreenshotRequest$Outbound,
  PostV1ServerScreenshotRequest
> = z.object({
  playerId: z.string(),
});

export function postV1ServerScreenshotRequestToJSON(
  postV1ServerScreenshotRequest: PostV1ServerScreenshotRequest,
): string {
  return JSON.stringify(
    PostV1ServerScreenshotRequest$outboundSchema.parse(
      postV1ServerScreenshotRequest,
    ),
  );
}

/** @internal */
export const PostV1ServerScreenshotResponse$inboundSchema: z.ZodMiniType<
  PostV1ServerScreenshotResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  screenshotUrl: types.optional(types.string()),
});

export function postV1ServerScreenshotResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1ServerScreenshotResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1ServerScreenshotResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1ServerScreenshotResponse' from JSON`,
  );
}
