/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostV1ServerExecRequest = {
  command: string;
  by?: string | undefined;
};

/**
 * Success
 */
export type PostV1ServerExecResponse = {
  success?: boolean | undefined;
  message?: string | undefined;
};

/** @internal */
export type PostV1ServerExecRequest$Outbound = {
  command: string;
  by?: string | undefined;
};

/** @internal */
export const PostV1ServerExecRequest$outboundSchema: z.ZodMiniType<
  PostV1ServerExecRequest$Outbound,
  PostV1ServerExecRequest
> = z.object({
  command: z.string(),
  by: z.optional(z.string()),
});

export function postV1ServerExecRequestToJSON(
  postV1ServerExecRequest: PostV1ServerExecRequest,
): string {
  return JSON.stringify(
    PostV1ServerExecRequest$outboundSchema.parse(postV1ServerExecRequest),
  );
}

/** @internal */
export const PostV1ServerExecResponse$inboundSchema: z.ZodMiniType<
  PostV1ServerExecResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  message: types.optional(types.string()),
});

export function postV1ServerExecResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1ServerExecResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1ServerExecResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1ServerExecResponse' from JSON`,
  );
}
