/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostV1ServerUnbanLastRequest = {
  count?: number | undefined;
  minutes?: number | undefined;
};

/**
 * Success
 */
export type PostV1ServerUnbanLastResponse = {
  success?: boolean | undefined;
  count?: number | undefined;
  message?: string | undefined;
};

/** @internal */
export type PostV1ServerUnbanLastRequest$Outbound = {
  count: number;
  minutes?: number | undefined;
};

/** @internal */
export const PostV1ServerUnbanLastRequest$outboundSchema: z.ZodMiniType<
  PostV1ServerUnbanLastRequest$Outbound,
  PostV1ServerUnbanLastRequest
> = z.object({
  count: z._default(z.int(), 1),
  minutes: z.optional(z.int()),
});

export function postV1ServerUnbanLastRequestToJSON(
  postV1ServerUnbanLastRequest: PostV1ServerUnbanLastRequest,
): string {
  return JSON.stringify(
    PostV1ServerUnbanLastRequest$outboundSchema.parse(
      postV1ServerUnbanLastRequest,
    ),
  );
}

/** @internal */
export const PostV1ServerUnbanLastResponse$inboundSchema: z.ZodMiniType<
  PostV1ServerUnbanLastResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  count: types.optional(types.number()),
  message: types.optional(types.string()),
});

export function postV1ServerUnbanLastResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1ServerUnbanLastResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1ServerUnbanLastResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1ServerUnbanLastResponse' from JSON`,
  );
}
