/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Success
 */
export type PostV1ServerUnbanAllResponse = {
  success?: boolean | undefined;
  count?: number | undefined;
  message?: string | undefined;
};

/** @internal */
export const PostV1ServerUnbanAllResponse$inboundSchema: z.ZodMiniType<
  PostV1ServerUnbanAllResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  count: types.optional(types.number()),
  message: types.optional(types.string()),
});

export function postV1ServerUnbanAllResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1ServerUnbanAllResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1ServerUnbanAllResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1ServerUnbanAllResponse' from JSON`,
  );
}
