/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostV1ServerBanOfflineDetails = {};

export type PostV1ServerBanOfflineRequest = {
  identifiers?: Array<string> | undefined;
  playerLicense?: string | undefined;
  reason: string;
  details?: PostV1ServerBanOfflineDetails | undefined;
  evidenceUrl?: string | undefined;
  by?: string | undefined;
};

/**
 * Success
 */
export type PostV1ServerBanOfflineResponse = {
  success?: boolean | undefined;
  banId?: string | undefined;
};

/** @internal */
export type PostV1ServerBanOfflineDetails$Outbound = {};

/** @internal */
export const PostV1ServerBanOfflineDetails$outboundSchema: z.ZodMiniType<
  PostV1ServerBanOfflineDetails$Outbound,
  PostV1ServerBanOfflineDetails
> = z.object({});

export function postV1ServerBanOfflineDetailsToJSON(
  postV1ServerBanOfflineDetails: PostV1ServerBanOfflineDetails,
): string {
  return JSON.stringify(
    PostV1ServerBanOfflineDetails$outboundSchema.parse(
      postV1ServerBanOfflineDetails,
    ),
  );
}

/** @internal */
export type PostV1ServerBanOfflineRequest$Outbound = {
  identifiers?: Array<string> | undefined;
  playerLicense?: string | undefined;
  reason: string;
  details?: PostV1ServerBanOfflineDetails$Outbound | undefined;
  evidenceUrl?: string | undefined;
  by?: string | undefined;
};

/** @internal */
export const PostV1ServerBanOfflineRequest$outboundSchema: z.ZodMiniType<
  PostV1ServerBanOfflineRequest$Outbound,
  PostV1ServerBanOfflineRequest
> = z.object({
  identifiers: z.optional(z.array(z.string())),
  playerLicense: z.optional(z.string()),
  reason: z.string(),
  details: z.optional(
    z.lazy(() => PostV1ServerBanOfflineDetails$outboundSchema),
  ),
  evidenceUrl: z.optional(z.string()),
  by: z.optional(z.string()),
});

export function postV1ServerBanOfflineRequestToJSON(
  postV1ServerBanOfflineRequest: PostV1ServerBanOfflineRequest,
): string {
  return JSON.stringify(
    PostV1ServerBanOfflineRequest$outboundSchema.parse(
      postV1ServerBanOfflineRequest,
    ),
  );
}

/** @internal */
export const PostV1ServerBanOfflineResponse$inboundSchema: z.ZodMiniType<
  PostV1ServerBanOfflineResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  banId: types.optional(types.string()),
});

export function postV1ServerBanOfflineResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1ServerBanOfflineResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1ServerBanOfflineResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1ServerBanOfflineResponse' from JSON`,
  );
}
