/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type PostV1ServerLookupRequest = {
  /**
   * Steam, License, Discord, or IP
   */
  identifier: string;
};

/**
 * Analysis result
 */
export type PostV1ServerLookupResponse = {
  dotDotDot?: models.PlayerAnalysis | undefined;
  notes?: Array<models.PlayerNote> | undefined;
};

/** @internal */
export type PostV1ServerLookupRequest$Outbound = {
  identifier: string;
};

/** @internal */
export const PostV1ServerLookupRequest$outboundSchema: z.ZodMiniType<
  PostV1ServerLookupRequest$Outbound,
  PostV1ServerLookupRequest
> = z.object({
  identifier: z.string(),
});

export function postV1ServerLookupRequestToJSON(
  postV1ServerLookupRequest: PostV1ServerLookupRequest,
): string {
  return JSON.stringify(
    PostV1ServerLookupRequest$outboundSchema.parse(postV1ServerLookupRequest),
  );
}

/** @internal */
export const PostV1ServerLookupResponse$inboundSchema: z.ZodMiniType<
  PostV1ServerLookupResponse,
  unknown
> = z.pipe(
  z.object({
    "...": types.optional(models.PlayerAnalysis$inboundSchema),
    notes: types.optional(z.array(models.PlayerNote$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "...": "dotDotDot",
    });
  }),
);

export function postV1ServerLookupResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1ServerLookupResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1ServerLookupResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1ServerLookupResponse' from JSON`,
  );
}
