/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostV1ServerBanRequest = {
  playerId: string;
  reason: string;
  duration?: number | undefined;
  evidence?: string | undefined;
  by?: string | undefined;
};

/**
 * Success
 */
export type PostV1ServerBanResponse = {
  success?: boolean | undefined;
  message?: string | undefined;
};

/** @internal */
export type PostV1ServerBanRequest$Outbound = {
  playerId: string;
  reason: string;
  duration?: number | undefined;
  evidence?: string | undefined;
  by?: string | undefined;
};

/** @internal */
export const PostV1ServerBanRequest$outboundSchema: z.ZodMiniType<
  PostV1ServerBanRequest$Outbound,
  PostV1ServerBanRequest
> = z.object({
  playerId: z.string(),
  reason: z.string(),
  duration: z.optional(z.int()),
  evidence: z.optional(z.string()),
  by: z.optional(z.string()),
});

export function postV1ServerBanRequestToJSON(
  postV1ServerBanRequest: PostV1ServerBanRequest,
): string {
  return JSON.stringify(
    PostV1ServerBanRequest$outboundSchema.parse(postV1ServerBanRequest),
  );
}

/** @internal */
export const PostV1ServerBanResponse$inboundSchema: z.ZodMiniType<
  PostV1ServerBanResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  message: types.optional(types.string()),
});

export function postV1ServerBanResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1ServerBanResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1ServerBanResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1ServerBanResponse' from JSON`,
  );
}
