/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostV1ServerAdminRemoveRequest = {
  discordId: string;
};

/**
 * Success
 */
export type PostV1ServerAdminRemoveResponse = {
  success?: boolean | undefined;
  message?: string | undefined;
};

/** @internal */
export type PostV1ServerAdminRemoveRequest$Outbound = {
  discordId: string;
};

/** @internal */
export const PostV1ServerAdminRemoveRequest$outboundSchema: z.ZodMiniType<
  PostV1ServerAdminRemoveRequest$Outbound,
  PostV1ServerAdminRemoveRequest
> = z.object({
  discordId: z.string(),
});

export function postV1ServerAdminRemoveRequestToJSON(
  postV1ServerAdminRemoveRequest: PostV1ServerAdminRemoveRequest,
): string {
  return JSON.stringify(
    PostV1ServerAdminRemoveRequest$outboundSchema.parse(
      postV1ServerAdminRemoveRequest,
    ),
  );
}

/** @internal */
export const PostV1ServerAdminRemoveResponse$inboundSchema: z.ZodMiniType<
  PostV1ServerAdminRemoveResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  message: types.optional(types.string()),
});

export function postV1ServerAdminRemoveResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1ServerAdminRemoveResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1ServerAdminRemoveResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1ServerAdminRemoveResponse' from JSON`,
  );
}
