/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AnalysisBanDetails = {};

export type AnalysisBanServer = {
  id?: string | undefined;
  name?: string | undefined;
  isCurrentServer?: boolean | undefined;
};

export type Identifier = {
  type?: string | undefined;
  value?: string | undefined;
};

export type MatchingIdentifier = {
  type?: string | undefined;
  value?: string | undefined;
};

export type AnalysisBanPlayer = {
  id?: string | undefined;
  playerName?: string | undefined;
  playTime?: number | undefined;
};

export type AnalysisBan = {
  id?: string | undefined;
  banId?: string | undefined;
  reason?: string | undefined;
  details?: AnalysisBanDetails | undefined;
  evidenceUrl?: string | undefined;
  bannedAt?: Date | undefined;
  expiresAt?: Date | undefined;
  bannedBy?: string | undefined;
  server?: AnalysisBanServer | undefined;
  identifiers?: Array<Identifier> | undefined;
  isDirectBan?: boolean | undefined;
  isAltAccountBan?: boolean | undefined;
  matchingIdentifiers?: Array<MatchingIdentifier> | undefined;
  player?: AnalysisBanPlayer | undefined;
};

/** @internal */
export const AnalysisBanDetails$inboundSchema: z.ZodMiniType<
  AnalysisBanDetails,
  unknown
> = z.object({});

export function analysisBanDetailsFromJSON(
  jsonString: string,
): SafeParseResult<AnalysisBanDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnalysisBanDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnalysisBanDetails' from JSON`,
  );
}

/** @internal */
export const AnalysisBanServer$inboundSchema: z.ZodMiniType<
  AnalysisBanServer,
  unknown
> = z.object({
  id: types.optional(types.string()),
  name: types.optional(types.string()),
  isCurrentServer: types.optional(types.boolean()),
});

export function analysisBanServerFromJSON(
  jsonString: string,
): SafeParseResult<AnalysisBanServer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnalysisBanServer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnalysisBanServer' from JSON`,
  );
}

/** @internal */
export const Identifier$inboundSchema: z.ZodMiniType<Identifier, unknown> = z
  .object({
    type: types.optional(types.string()),
    value: types.optional(types.string()),
  });

export function identifierFromJSON(
  jsonString: string,
): SafeParseResult<Identifier, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Identifier$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Identifier' from JSON`,
  );
}

/** @internal */
export const MatchingIdentifier$inboundSchema: z.ZodMiniType<
  MatchingIdentifier,
  unknown
> = z.object({
  type: types.optional(types.string()),
  value: types.optional(types.string()),
});

export function matchingIdentifierFromJSON(
  jsonString: string,
): SafeParseResult<MatchingIdentifier, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MatchingIdentifier$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MatchingIdentifier' from JSON`,
  );
}

/** @internal */
export const AnalysisBanPlayer$inboundSchema: z.ZodMiniType<
  AnalysisBanPlayer,
  unknown
> = z.object({
  id: types.optional(types.string()),
  playerName: types.optional(types.string()),
  playTime: types.optional(types.number()),
});

export function analysisBanPlayerFromJSON(
  jsonString: string,
): SafeParseResult<AnalysisBanPlayer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnalysisBanPlayer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnalysisBanPlayer' from JSON`,
  );
}

/** @internal */
export const AnalysisBan$inboundSchema: z.ZodMiniType<AnalysisBan, unknown> = z
  .object({
    id: types.optional(types.string()),
    banId: types.optional(types.string()),
    reason: types.optional(types.string()),
    details: types.optional(z.lazy(() => AnalysisBanDetails$inboundSchema)),
    evidenceUrl: types.optional(types.string()),
    bannedAt: types.optional(types.date()),
    expiresAt: types.optional(types.date()),
    bannedBy: types.optional(types.string()),
    server: types.optional(z.lazy(() => AnalysisBanServer$inboundSchema)),
    identifiers: types.optional(
      z.array(z.lazy(() => Identifier$inboundSchema)),
    ),
    isDirectBan: types.optional(types.boolean()),
    isAltAccountBan: types.optional(types.boolean()),
    matchingIdentifiers: types.optional(
      z.array(z.lazy(() => MatchingIdentifier$inboundSchema)),
    ),
    player: types.optional(z.lazy(() => AnalysisBanPlayer$inboundSchema)),
  });

export function analysisBanFromJSON(
  jsonString: string,
): SafeParseResult<AnalysisBan, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnalysisBan$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnalysisBan' from JSON`,
  );
}
