/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type BanPublicDetails = {};

export type BanPublic = {
  id?: string | undefined;
  /**
   * Player Name
   */
  player?: string | undefined;
  /**
   * Server Name
   */
  server?: string | undefined;
  reason?: string | undefined;
  details?: BanPublicDetails | undefined;
  evidence?: string | undefined;
  playTime?: number | undefined;
  oldNames?: Array<string> | undefined;
  identifiers?: Array<string> | undefined;
  oldIdentifiers?: Array<string> | undefined;
  bannedAt?: Date | undefined;
  expiresAt?: Date | undefined;
  bannedBy?: string | undefined;
};

/** @internal */
export const BanPublicDetails$inboundSchema: z.ZodMiniType<
  BanPublicDetails,
  unknown
> = z.object({});

export function banPublicDetailsFromJSON(
  jsonString: string,
): SafeParseResult<BanPublicDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BanPublicDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BanPublicDetails' from JSON`,
  );
}

/** @internal */
export const BanPublic$inboundSchema: z.ZodMiniType<BanPublic, unknown> = z
  .object({
    id: types.optional(types.string()),
    player: types.optional(types.string()),
    server: types.optional(types.string()),
    reason: types.optional(types.string()),
    details: types.optional(z.lazy(() => BanPublicDetails$inboundSchema)),
    evidence: types.optional(types.string()),
    playTime: types.optional(types.number()),
    oldNames: types.optional(z.array(types.string())),
    identifiers: types.optional(z.array(types.string())),
    oldIdentifiers: types.optional(z.array(types.string())),
    bannedAt: types.optional(types.date()),
    expiresAt: types.optional(types.date()),
    bannedBy: types.optional(types.string()),
  });

export function banPublicFromJSON(
  jsonString: string,
): SafeParseResult<BanPublic, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BanPublic$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BanPublic' from JSON`,
  );
}
