/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { AnalysisBan, AnalysisBan$inboundSchema } from "./analysisban.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type PlayerAnalysisPlayer = {
  id?: string | undefined;
  playerName?: string | undefined;
  playerLicense?: string | undefined;
  oldNames?: Array<string> | undefined;
  identifiers?: Array<string> | undefined;
  oldIdentifiers?: Array<string> | undefined;
  firstJoin?: Date | undefined;
  lastJoin?: Date | undefined;
  playTime?: number | undefined;
};

export type AltAccountServer = {
  id?: string | undefined;
  name?: string | undefined;
  isCurrentServer?: boolean | undefined;
};

export type AltAccount = {
  id?: string | undefined;
  playerName?: string | undefined;
  playerLicense?: string | undefined;
  firstJoin?: Date | undefined;
  lastJoin?: Date | undefined;
  playTime?: number | undefined;
  server?: AltAccountServer | undefined;
  matchingIdentifiers?: Array<string> | undefined;
  identifiersCount?: number | undefined;
};

export type Role = {
  roleId?: string | undefined;
  roleName?: string | undefined;
  roleColor?: string | undefined;
};

export type DiscordCheatServersLookupServer = {
  serverIconUrl?: string | undefined;
  serverName?: string | undefined;
  serverGuildId?: string | undefined;
  roles?: Array<Role> | undefined;
};

export type DiscordCheatServersLookup = {
  isInCheatServer?: boolean | undefined;
  totalServers?: number | undefined;
  servers?: Array<DiscordCheatServersLookupServer> | undefined;
};

export type PlayerAnalysisDetails = {};

export type BansHistory = {
  server?: string | undefined;
  reason?: string | undefined;
  details?: PlayerAnalysisDetails | undefined;
  evidenceUrl?: string | undefined;
  bannedAt?: Date | undefined;
};

export const RiskLevel = {
  Low: "LOW",
  Medium: "MEDIUM",
  High: "HIGH",
  Critical: "CRITICAL",
} as const;
export type RiskLevel = OpenEnum<typeof RiskLevel>;

export type ThreatScore = {
  score?: number | undefined;
  riskLevel?: RiskLevel | undefined;
  warnings?: Array<string> | undefined;
};

export type PlayerAnalysis = {
  player?: PlayerAnalysisPlayer | undefined;
  altAccounts?: Array<AltAccount> | undefined;
  discordCheatServersLookup?: DiscordCheatServersLookup | undefined;
  playerBans?: Array<AnalysisBan> | undefined;
  sameServerAltBans?: Array<AnalysisBan> | undefined;
  crossServerBans?: Array<AnalysisBan> | undefined;
  bansHistory?: Array<BansHistory> | undefined;
  threatScore?: ThreatScore | undefined;
};

/** @internal */
export const PlayerAnalysisPlayer$inboundSchema: z.ZodMiniType<
  PlayerAnalysisPlayer,
  unknown
> = z.object({
  id: types.optional(types.string()),
  playerName: types.optional(types.string()),
  playerLicense: types.optional(types.string()),
  oldNames: types.optional(z.array(types.string())),
  identifiers: types.optional(z.array(types.string())),
  oldIdentifiers: types.optional(z.array(types.string())),
  firstJoin: types.optional(types.date()),
  lastJoin: types.optional(types.date()),
  playTime: types.optional(types.number()),
});

export function playerAnalysisPlayerFromJSON(
  jsonString: string,
): SafeParseResult<PlayerAnalysisPlayer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlayerAnalysisPlayer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlayerAnalysisPlayer' from JSON`,
  );
}

/** @internal */
export const AltAccountServer$inboundSchema: z.ZodMiniType<
  AltAccountServer,
  unknown
> = z.object({
  id: types.optional(types.string()),
  name: types.optional(types.string()),
  isCurrentServer: types.optional(types.boolean()),
});

export function altAccountServerFromJSON(
  jsonString: string,
): SafeParseResult<AltAccountServer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AltAccountServer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AltAccountServer' from JSON`,
  );
}

/** @internal */
export const AltAccount$inboundSchema: z.ZodMiniType<AltAccount, unknown> = z
  .object({
    id: types.optional(types.string()),
    playerName: types.optional(types.string()),
    playerLicense: types.optional(types.string()),
    firstJoin: types.optional(types.date()),
    lastJoin: types.optional(types.date()),
    playTime: types.optional(types.number()),
    server: types.optional(z.lazy(() => AltAccountServer$inboundSchema)),
    matchingIdentifiers: types.optional(z.array(types.string())),
    identifiersCount: types.optional(types.number()),
  });

export function altAccountFromJSON(
  jsonString: string,
): SafeParseResult<AltAccount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AltAccount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AltAccount' from JSON`,
  );
}

/** @internal */
export const Role$inboundSchema: z.ZodMiniType<Role, unknown> = z.object({
  roleId: types.optional(types.string()),
  roleName: types.optional(types.string()),
  roleColor: types.optional(types.string()),
});

export function roleFromJSON(
  jsonString: string,
): SafeParseResult<Role, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Role$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Role' from JSON`,
  );
}

/** @internal */
export const DiscordCheatServersLookupServer$inboundSchema: z.ZodMiniType<
  DiscordCheatServersLookupServer,
  unknown
> = z.object({
  serverIconUrl: types.optional(types.string()),
  serverName: types.optional(types.string()),
  serverGuildId: types.optional(types.string()),
  roles: types.optional(z.array(z.lazy(() => Role$inboundSchema))),
});

export function discordCheatServersLookupServerFromJSON(
  jsonString: string,
): SafeParseResult<DiscordCheatServersLookupServer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DiscordCheatServersLookupServer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DiscordCheatServersLookupServer' from JSON`,
  );
}

/** @internal */
export const DiscordCheatServersLookup$inboundSchema: z.ZodMiniType<
  DiscordCheatServersLookup,
  unknown
> = z.object({
  isInCheatServer: types.optional(types.boolean()),
  totalServers: types.optional(types.number()),
  servers: types.optional(
    z.array(z.lazy(() => DiscordCheatServersLookupServer$inboundSchema)),
  ),
});

export function discordCheatServersLookupFromJSON(
  jsonString: string,
): SafeParseResult<DiscordCheatServersLookup, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DiscordCheatServersLookup$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DiscordCheatServersLookup' from JSON`,
  );
}

/** @internal */
export const PlayerAnalysisDetails$inboundSchema: z.ZodMiniType<
  PlayerAnalysisDetails,
  unknown
> = z.object({});

export function playerAnalysisDetailsFromJSON(
  jsonString: string,
): SafeParseResult<PlayerAnalysisDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlayerAnalysisDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlayerAnalysisDetails' from JSON`,
  );
}

/** @internal */
export const BansHistory$inboundSchema: z.ZodMiniType<BansHistory, unknown> = z
  .object({
    server: types.optional(types.string()),
    reason: types.optional(types.string()),
    details: types.optional(z.lazy(() => PlayerAnalysisDetails$inboundSchema)),
    evidenceUrl: types.optional(types.string()),
    bannedAt: types.optional(types.date()),
  });

export function bansHistoryFromJSON(
  jsonString: string,
): SafeParseResult<BansHistory, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BansHistory$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BansHistory' from JSON`,
  );
}

/** @internal */
export const RiskLevel$inboundSchema: z.ZodMiniType<RiskLevel, unknown> =
  openEnums.inboundSchema(RiskLevel);

/** @internal */
export const ThreatScore$inboundSchema: z.ZodMiniType<ThreatScore, unknown> = z
  .object({
    score: types.optional(types.number()),
    riskLevel: types.optional(RiskLevel$inboundSchema),
    warnings: types.optional(z.array(types.string())),
  });

export function threatScoreFromJSON(
  jsonString: string,
): SafeParseResult<ThreatScore, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ThreatScore$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ThreatScore' from JSON`,
  );
}

/** @internal */
export const PlayerAnalysis$inboundSchema: z.ZodMiniType<
  PlayerAnalysis,
  unknown
> = z.object({
  player: types.optional(z.lazy(() => PlayerAnalysisPlayer$inboundSchema)),
  altAccounts: types.optional(z.array(z.lazy(() => AltAccount$inboundSchema))),
  discordCheatServersLookup: types.optional(
    z.lazy(() => DiscordCheatServersLookup$inboundSchema),
  ),
  playerBans: types.optional(z.array(AnalysisBan$inboundSchema)),
  sameServerAltBans: types.optional(z.array(AnalysisBan$inboundSchema)),
  crossServerBans: types.optional(z.array(AnalysisBan$inboundSchema)),
  bansHistory: types.optional(z.array(z.lazy(() => BansHistory$inboundSchema))),
  threatScore: types.optional(z.lazy(() => ThreatScore$inboundSchema)),
});

export function playerAnalysisFromJSON(
  jsonString: string,
): SafeParseResult<PlayerAnalysis, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlayerAnalysis$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlayerAnalysis' from JSON`,
  );
}
