/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type PlayerNote = {
  id?: string | undefined;
  authorId?: string | undefined;
  authorName?: string | undefined;
  authorImage?: string | undefined;
  isPinned?: boolean | undefined;
  content?: string | undefined;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
};

/** @internal */
export const PlayerNote$inboundSchema: z.ZodMiniType<PlayerNote, unknown> = z
  .object({
    id: types.optional(types.string()),
    authorId: types.optional(types.string()),
    authorName: types.optional(types.string()),
    authorImage: types.optional(types.string()),
    isPinned: types.optional(types.boolean()),
    content: types.optional(types.string()),
    createdAt: types.optional(types.date()),
    updatedAt: types.optional(types.date()),
  });

export function playerNoteFromJSON(
  jsonString: string,
): SafeParseResult<PlayerNote, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlayerNote$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlayerNote' from JSON`,
  );
}
