/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type Security = {
  apiKeyAuth?: string | undefined;
  apiSecretAuth?: string | undefined;
};

/** @internal */
export type Security$Outbound = {
  ApiKeyAuth?: string | undefined;
  ApiSecretAuth?: string | undefined;
};

/** @internal */
export const Security$outboundSchema: z.ZodMiniType<
  Security$Outbound,
  Security
> = z.pipe(
  z.object({
    apiKeyAuth: z.optional(z.string()),
    apiSecretAuth: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      apiKeyAuth: "ApiKeyAuth",
      apiSecretAuth: "ApiSecretAuth",
    });
  }),
);

export function securityToJSON(security: Security): string {
  return JSON.stringify(Security$outboundSchema.parse(security));
}
