/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ServerBanHistoryDetails = {};

export type ServerBanHistory = {
  player?: string | undefined;
  reason?: string | undefined;
  details?: ServerBanHistoryDetails | undefined;
  playTime?: number | undefined;
  evidence?: string | undefined;
  bannedAt?: Date | undefined;
};

/** @internal */
export const ServerBanHistoryDetails$inboundSchema: z.ZodMiniType<
  ServerBanHistoryDetails,
  unknown
> = z.object({});

export function serverBanHistoryDetailsFromJSON(
  jsonString: string,
): SafeParseResult<ServerBanHistoryDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ServerBanHistoryDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServerBanHistoryDetails' from JSON`,
  );
}

/** @internal */
export const ServerBanHistory$inboundSchema: z.ZodMiniType<
  ServerBanHistory,
  unknown
> = z.object({
  player: types.optional(types.string()),
  reason: types.optional(types.string()),
  details: types.optional(z.lazy(() => ServerBanHistoryDetails$inboundSchema)),
  playTime: types.optional(types.number()),
  evidence: types.optional(types.string()),
  bannedAt: types.optional(types.date()),
});

export function serverBanHistoryFromJSON(
  jsonString: string,
): SafeParseResult<ServerBanHistory, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ServerBanHistory$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServerBanHistory' from JSON`,
  );
}
