/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ServerLogDetails = {};

export type ServerLog = {
  id?: string | undefined;
  type?: string | undefined;
  details?: ServerLogDetails | undefined;
  timestamp?: Date | undefined;
  /**
   * Member ID or Name
   */
  executor?: string | undefined;
  /**
   * Player ID or License
   */
  target?: string | undefined;
};

/** @internal */
export const ServerLogDetails$inboundSchema: z.ZodMiniType<
  ServerLogDetails,
  unknown
> = z.object({});

export function serverLogDetailsFromJSON(
  jsonString: string,
): SafeParseResult<ServerLogDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ServerLogDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServerLogDetails' from JSON`,
  );
}

/** @internal */
export const ServerLog$inboundSchema: z.ZodMiniType<ServerLog, unknown> = z
  .object({
    id: types.optional(types.string()),
    type: types.optional(types.string()),
    details: types.optional(z.lazy(() => ServerLogDetails$inboundSchema)),
    timestamp: types.optional(types.date()),
    executor: types.optional(types.string()),
    target: types.optional(types.string()),
  });

export function serverLogFromJSON(
  jsonString: string,
): SafeParseResult<ServerLog, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ServerLog$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServerLog' from JSON`,
  );
}
